-- PocketBase Schema Creation Script
-- 
-- Note: PocketBase doesn't use SQL directly, but this document serves as
-- a reference for the expected schema structure.
-- 
-- Use the PocketBase Admin Panel to create these collections manually,
-- or use the PocketBase CLI/API to create them programmatically.

-- ============================================
-- Collection: mosques
-- ============================================
-- Fields:
--   - id (auto-generated)
--   - name (Text, required)
--   - name_bm (Text, optional)
--   - address (Text, required)
--   - state (Text, required) - Malaysian state
--   - lat (Number, required) - Latitude
--   - lng (Number, required) - Longitude
--   - description (Text, optional)
--   - description_bm (Text, optional)
--   - status (Select: pending, approved, rejected, default: pending)
--   - created_by (Relation: users, required)
--   - created (auto-generated)
--   - updated (auto-generated)

-- ============================================
-- Collection: amenities
-- ============================================
-- Fields:
--   - id (auto-generated)
--   - key (Text, required, unique) - e.g., "parking", "wudu"
--   - label_bm (Text, required) - Bahasa Malaysia label
--   - label_en (Text, required) - English label
--   - icon (Text, optional) - Icon identifier
--   - order (Number, default: 0) - Display order
--   - created (auto-generated)
--   - updated (auto-generated)

-- ============================================
-- Collection: mosque_amenities
-- ============================================
-- Fields:
--   - id (auto-generated)
--   - mosque_id (Relation: mosques, required)
--   - amenity_id (Relation: amenities, optional) - null for custom amenities
--   - details (JSON, default: {}) - MosqueAmenityDetails
--     {
--       "notes": "string (optional)",
--       "custom_name": "string (optional, for custom amenities)",
--       "custom_name_en": "string (optional, for custom amenities)",
--       "custom_icon": "string (optional, for custom amenities)"
--     }
--   - verified (Boolean, default: false)
--   - created (auto-generated)
--   - updated (auto-generated)

-- ============================================
-- Collection: activities
-- ============================================
-- Fields:
--   - id (auto-generated)
--   - mosque_id (Relation: mosques, required)
--   - title (Text, required)
--   - title_bm (Text, optional)
--   - description (Text, optional)
--   - description_bm (Text, optional)
--   - type (Select: one_off, recurring, fixed, required)
--   - schedule_json (JSON, required) - ActivitySchedule
--     For one_off:
--     {
--       "date": "ISO date string",
--       "time": "HH:mm format"
--     }
--     For recurring:
--     {
--       "recurrence": "daily|weekly|monthly",
--       "days_of_week": [0-6], // 0=Sunday
--       "start_date": "ISO date string",
--       "end_date": "ISO date string (optional)"
--     }
--   - start_date (Date, optional)
--   - end_date (Date, optional)
--   - status (Select: active, cancelled, default: active)
--   - created_by (Relation: users, required)
--   - created (auto-generated)
--   - updated (auto-generated)

-- ============================================
-- Collection: submissions
-- ============================================
-- Fields:
--   - id (auto-generated)
--   - type (Select: new_mosque, edit_mosque, required)
--   - mosque_id (Relation: mosques, optional) - null for new_mosque
--   - data (JSON, required) - Full mosque data object
--   - status (Select: pending, approved, rejected, default: pending)
--   - submitted_by (Relation: users, required)
--   - submitted_at (Date, required)
--   - reviewed_by (Relation: users, optional)
--   - reviewed_at (Date, optional)
--   - rejection_reason (Text, optional)
--   - created (auto-generated)
--   - updated (auto-generated)

-- ============================================
-- Collection: audit_logs
-- ============================================
-- Fields:
--   - id (auto-generated)
--   - actor_id (Relation: users, required)
--   - action (Text, required) - e.g., "create", "update", "delete", "approve", "reject"
--   - entity_type (Text, required) - e.g., "mosque", "submission", "user"
--   - entity_id (Text, required)
--   - before (JSON, optional) - Snapshot before change
--   - after (JSON, optional) - Snapshot after change
--   - timestamp (Date, required)
--   - ip_address (Text, optional)
--   - user_agent (Text, optional)
--   - created (auto-generated)
--   - updated (auto-generated)

-- ============================================
-- Collection: users (PocketBase built-in)
-- ============================================
-- PocketBase provides a built-in users collection.
-- You may want to extend it with:
--   - trust_score (Number, default: 0)
--   - role (Select: user, admin, default: user)
--   - avatar (File, optional)
--   - username (Text, optional)

-- ============================================
-- Indexes (for performance)
-- ============================================
-- Recommended indexes:
--   - mosques: state, status, lat, lng
--   - mosque_amenities: mosque_id, amenity_id
--   - activities: mosque_id, status
--   - submissions: status, submitted_by, submitted_at
--   - audit_logs: actor_id, entity_type, timestamp

-- ============================================
-- Validation Rules (examples)
-- ============================================
-- mosques.lat: >= -90 && <= 90
-- mosques.lng: >= -180 && <= 180
-- mosques.state: In list of Malaysian states
-- amenities.key: Unique, lowercase, alphanumeric + underscore
-- activities.schedule_json: Valid JSON matching ActivitySchedule structure

